[build]
  command = "yarn install && yarn prisma:generate && yarn reset-db"
  functions = "functions"
  publish = "functions"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"


[functions]

[functions.postInvoices]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.getInvoice]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.updateInvoice]
  external_node_modules = [
    "module-one",
    "module-two"
  ]

[functions.deleteInvoice]
  external_node_modules = [
    "module-one",
    "module-two"
  ]
